// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

// `Time` is a simple type only containing the current time as
// a unix epoch timestamp and a string timestamp.
type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
